# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  auction.uksouth.cloudapp.azure.com:
    site_hosts:
      - canonical: auction.uksouth.cloudapp.azure.com
        redirects:
          - www.auction.uksouth.cloudapp.azure.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:elvinos/AuctionSite.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    site_install: false
    db_create: false
    ensure_wordpress: false
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
